### ISSUE TITLE
[Bug] "File not found" error

### ISSUE THREAD

**Issue by SnzMaxim** [mindustry-antigrief/mindustry-client#165] opened 2023-06-05 22:49 UTC
**Foo's client starts normally at first, but after restarting I got a "File not found" error**
![image](https://github.com/mindustry-antigrief/mindustry-client/assets/72713833/274f3f93-11a9-4c21-a80a-80439d716f45)
Here is crash report
[crash-report-06_05_2023_03_29_55.txt](https://github.com/mindustry-antigrief/mindustry-client/files/11658262/crash-report-06_05_2023_03_29_55.txt)
Problem in boss1 music file, but I reinstalled **Mindustry and Foo's client** several times and it didn't help
![image](https://github.com/mindustry-antigrief/mindustry-client/assets/72713833/8a393e48-f6f3-40f6-80c0-c64653ea1c23)
_I first went to the discord server, but didn't get help._

**Comment by buthed010203** [comment] 2023-06-05 22:58
That is... odd, try deleting the file and opening the game again

**Comment by buthed010203** [comment] 2023-06-05 23:06
Think I just found the issue, should be fixed after it finishes building

**Comment by SnzMaxim** [comment] 2023-06-05 23:09
Okay i solved this problem. It just took two days. I have **"Mod Library"** mod, which foo's client doesn't start.
I turn it off and client starts fine. **Thx for help XD** (for some reason others have no problems with this mod)

**Comment by SnzMaxim** [comment] 2023-06-05 23:10
Okay i just close issue

**Comment by buthed010203** [comment] 2023-06-05 23:11
> Okay i solved this problem. It just took two days. I have **"Mod Library"** mod, which foo's client doesn't start. I turn it off and client starts fine. **Thx for help XD** (for some reason others have no problems with this mod)

Weird, I still think this issue may be fixed with the build that is currently building

**Comment by buthed010203** [comment] 2023-06-05 23:15
Try using the mod on the lastest version of foos

**Comment by SnzMaxim** [comment] 2023-06-05 23:34
oh new bug. After installation i got release mindustry build instead of steam build. After a clean installation of Mindustry and client, the Mindustry build changes after a restart.

**Comment by buthed010203** [comment] 2023-06-05 23:38
Instead of building a version for steam and a version for non steam, we only build one version and automatically set the version modifier to steam when the jar is located within `/steamapps/common/Mindustry/`.

**Comment by SnzMaxim** [comment] 2023-06-06 00:13
**For some reason "Mod library" mod now doesn't work with steam build mindustry, and if i download foo's client using command then all works fine. But if i turn on "Mod Library" then my "steam build" became "release build" and path to jar "steamapps/....." become "java/jdk-17".
And why this exists**
![image](https://github.com/mindustry-antigrief/mindustry-client/assets/72713833/261afe92-288d-4899-accd-b1d60c6e1f3b)
I think i broke all that i can

**Comment by buthed010203** [comment] 2023-06-06 00:31
Mind linking me to the mod?
Those files are from bouncycastle and are unpacked from the main jar as oracle jre doesn't like them if they're included in the jar itself.

**Comment by SnzMaxim** [comment] 2023-06-06 00:33
Sure, https://github.com/redstonneur1256/mindustry-modlib
I think i just need to delete this mod. It solves any problem :d And im tired and i go to sleep

**Comment by buthed010203** [comment] 2023-06-06 00:37
My best guess is that the mixins are messing with the path somehow, unless red knows there's not really much that can be done about this. You may be able to add a file named `steam_appid.txt` to the same folder as your jar and make the contents `1127400`.

**Comment by SnzMaxim** [comment] 2023-06-06 00:45
What i need to do ☠☠💀💀💀💀
![image](https://github.com/mindustry-antigrief/mindustry-client/assets/72713833/e9cbb887-47d4-4852-99f0-a5a9b4a9ce4d)

**Comment by buthed010203** [comment] 2023-06-06 00:46
No clue anymore, ask @Redstonneur1256 if he has any idea

**Comment by SnzMaxim** [comment] 2023-06-06 00:47
Okay thanks for help

**Closed as completed by buthed010203** 2023-06-06 00:46 UTC

**Comment by Redstonneur1256** [comment] 2023-06-06 05:21
Crash report indicates no mod and I cannot reproduce on latest build
